#ifndef __BUTTON_CONF_H__
#define __BUTTON_CONF_H__

#define BUTTON_HANDLER_CAPACITY             3
#define BUTTON_MULTI_CLICK_EVENT_CAPACITY   5

#define KEY_UPDATE_PER_MS                   20UL

#define KEY_SINGLE_PRESS_THRES_MS           40UL
#define KEY_SHORT_PRESS_THRES_MS            600UL
#define KEY_MIDDLE_PRESS_THRES_MS           1200UL
#define KEY_LONG_PRESS_THRES_MS             4000UL
#define KEY_DOUBLE_CLICK_WINDOW_MS          300UL
#define KEY_MULTI_CLICK_WINDOW_MS           300UL
#define KEY_STARTUP_SHORT_PRESS_THRES_MS    200UL
#define KEY_STARTUP_LONG_PRESS_THRES_MS     5000UL
#define KEY_PRESS_VALID_RELEASE_THRES_MS    1500UL
#define KEY_PRESS_OVERFLOW_MS               60000UL

#define KEY_SINGLE_PRESS_THRES_COUNT        (KEY_SINGLE_PRESS_THRES_MS / KEY_UPDATE_PER_MS)
#define KEY_SHORT_PRESS_THRES_COUNT         (KEY_SHORT_PRESS_THRES_MS / KEY_UPDATE_PER_MS)
#define KEY_MIDDLE_PRESS_THRES_COUNT        (KEY_MIDDLE_PRESS_THRES_MS / KEY_UPDATE_PER_MS)
#define KEY_LONG_PRESS_THRES_COUNT          (KEY_LONG_PRESS_THRES_MS / KEY_UPDATE_PER_MS)
#define KEY_DOUBLE_CLICK_WINDOW_COUNT       (KEY_DOUBLE_CLICK_WINDOW_MS / KEY_UPDATE_PER_MS)
#define KEY_MULTI_CLICK_VALID_COUNT         (KEY_MULTI_CLICK_WINDOW_MS / KEY_UPDATE_PER_MS)
#define KEY_STARTUP_SHORT_PRESS_THRES_COUNT	(KEY_STARTUP_SHORT_PRESS_THRES_MS / KEY_UPDATE_PER_MS)
#define KEY_STARTUP_LONG_PRESS_THRES_COUNT  (KEY_STARTUP_LONG_PRESS_THRES_MS / KEY_UPDATE_PER_MS)
#define KEY_PRESS_VALID_RELEASE_THRES_COUNT (KEY_PRESS_VALID_RELEASE_THRES_MS / KEY_UPDATE_PER_MS)
#define KEY_PRESS_OVERFLOW_COUNT		    (KEY_PRESS_OVERFLOW_MS / KEY_UPDATE_PER_MS)


typedef enum {
    BUTTON_TRIGGER_LEVEL_LOW = 0,
    BUTTON_TRIGGER_LEVEL_HIGH
} BUTTON_TRIGGER_LEVEL_E;


typedef enum {
    BUTTON_SINGLE_CLICK = 0,
    BUTTON_SHORT_PRESS,
    BUTTON_MIDDLE_PRESS,
    BUTTON_LONG_PRESS,
    BUTTON_SHORT_PRESS_RELEASE,
    BUTTON_MIDDLE_PRESS_RELEASE,
    BUTTON_LONG_PRESS_RELEASE,
    BUTTON_DOUBLE_CLICK,
    BUTTON_TRIGGER,
    BUTTON_RELEASE,
	BUTTON_STARTUP_SHORT_PRESS,
    BUTTON_STARTUP_LONG_PRESS,
    BUTTON_MULTI_CLICK
} BUTTON_EVENT_E;


#endif
