#ifndef __APP_FREERTOS_H__
#define __APP_FREERTOS_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "FreeRTOS.h"
#include "cmsis_os2.h"
#include "main.h"
#include "task.h"

/*
  *********************************************************************************************
    This file was not automatically generated by cubemx and needs to be manually synchronized
  *********************************************************************************************
*/
// clang-format off
#define CFG_INIT_BIT        (1 << 0)
#define LOG_INIT_BIT        (1 << 1)
#define COMMU_INIT_BIT      (1 << 2)
#define RS485_INIT_BIT      (1 << 3)

#define IS_VALID_NOTIFICATION(_save_noti, bit)                                                                         \
    ((_save_noti) != osErrorTimeout && (_save_noti) != osErrorResource && ((bit) & (_save_noti)))

// clang-format on

// extern osThreadId_t cfg_initHandle;
// extern osThreadId_t ext_adcHandle;
// extern osThreadId_t local_adcHandle;
// extern osThreadId_t commu_initHandle;
// extern osThreadId_t runHandle;
// extern osThreadId_t brushed_motorHandle;
// extern osThreadId_t control_ifHandle;
// extern osThreadId_t sensor_dpHandle;

// extern osTimerId_t os_mgntHandle;

// extern osMutexId_t crc_hw_mutexHandle;

extern osEventFlagsId_t os_init_eventHandle;

void NS_FREERTOS_Init(void);

// #define CRC_HW_MUTEX crc_hw_mutexHandle

// #define OS_MGNT_TIMER os_mgntHandle

#ifdef __cplusplus
}
#endif

#endif
