 /**
  @defgroup bookoo_error_def BooKoo IoT product global error definitions.
  @{

  @brief Global Error definitions
*/

#ifndef BOOKOO_ERROR_DEF_H__
#define BOOKOO_ERROR_DEF_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

void app_warning_handler_bare(uint16_t _warning_code);

typedef enum {
    ERR_NONE = 0x000,
    ERR_FAIL = -0x001,
    ERR_INVALID_ARG = -0x002,
    ERR_INVALID_POINTER = -0x003,
    ERR_INVALID_LEN = -0x004,
    ERR_NO_MEM = -0x005,
    ERR_NOT_INIT = -0x006,
    ERR_TIMEOUT = -0x007,
    ERR_NOT_EXIST = -0x008,
    ERR_OUT_OF_RANGE = -0x009,
    ERR_WRITE_FAIL = -0x00A,
    ERR_READ_FAIL = -0x00B,
    ERR_BUSY = -0x00C,
    ERR_RESOURCE_FULL = -0x00D,
    ERR_REINIT = -0x00E,
    ERR_ALREADY_EXIST = -0x00F,
    ERR_NOT_SUPPORTED = -0x010,
    ERR_WOULD_BLOCK = -0x011,
    ERR_DEADLOCK = -0x012,
    ERR_PERMISSION = -0x013,
    ERR_OVERFLOW = -0x014,
    ERR_UNDERFLOW = -0x015,
    ERR_INVALID_STATE = -0x016,
    ERR_INVALID_TYPE = -0x017,
    
    ERR_FLASH_BASE = -0x100,
    ERR_FLASH_INVALID_ARG = -0x101,
    ERR_FLASH_INVALID_POINTER = -0x102,
    ERR_FLASH_ACTIVE_NOT_EXIST = -0x103,
    ERR_FLASH_INVALID_CRC = -0x104,
    ERR_FLASH_WRITE_PROTECT = -0x105,
    ERR_FLASH_ERASE_FAIL = -0x106,
    ERR_FLASH_WRITE_FAIL = -0x107,
    ERR_FLASH_READ_FAIL = -0x108,
    
} SYSTEM_ERROR_CODE_E;

/** @defgroup Error Codes Base number definitions
 * @{ */
#define BOOKOO_ERROR_SYS_RESOURCE_BASE_NUM  	    (0x4100)    ///< System resource level error base
#define BOOKOO_ERROR_SYS_MODULE_BASE_NUM  		    (0x4200)    ///< System module level error base
#define BOOKOO_ERROR_SYS_PERIPHERAL_BASE_NUM 	    (0x4300)    ///< System peripheral error base
/** @} */

#define BOOKOO_ERROR_HARDFAULT                      (BOOKOO_ERROR_SYS_RESOURCE_BASE_NUM + 1)
#define BOOKOO_ERROR_THREADDEAD                     (BOOKOO_ERROR_SYS_RESOURCE_BASE_NUM + 2)
#define BOOKOO_ERROR_THREADHEAPFAULT                (BOOKOO_ERROR_SYS_RESOURCE_BASE_NUM + 3)

#define BOOKOO_ERROR_DFU_BOOTLOADER_FAIL            (BOOKOO_ERROR_SYS_MODULE_BASE_NUM + 1)
#define BOOKOO_ERROR_DFU_CLIENTCOMM_FAIL			(BOOKOO_ERROR_SYS_MODULE_BASE_NUM + 2)
#define BOOKOO_ERROR_DFU_OTHERS_FAIL                (BOOKOO_ERROR_SYS_MODULE_BASE_NUM + 3)
#define BOOKOO_ERROR_TIMING_FAIL                    (BOOKOO_ERROR_SYS_MODULE_BASE_NUM + 4)
#define BOOKOO_ERROR_DISP_UPDATE_FAIL               (BOOKOO_ERROR_SYS_MODULE_BASE_NUM + 5)
#define BOOKOO_ERROR_DISP_WAKEUP_FAIL               (BOOKOO_ERROR_SYS_MODULE_BASE_NUM + 6)
#define BOOKOO_ERROR_MASS_UPDATE_FAIL               (BOOKOO_ERROR_SYS_MODULE_BASE_NUM + 7)
#define BOOKOO_ERROR_MASS_WAKEUP_FAIL               (BOOKOO_ERROR_SYS_MODULE_BASE_NUM + 8)
#define BOOKOO_ERROR_BTN_TIMER_FAIL                 (BOOKOO_ERROR_SYS_MODULE_BASE_NUM + 9)
#define BOOKOO_ERROR_BTN_ALLBAND_FAIL               (BOOKOO_ERROR_SYS_MODULE_BASE_NUM + 10)
#define BOOKOO_ERROR_BLE_CONNPARAMS_FAIL			(BOOKOO_ERROR_SYS_MODULE_BASE_NUM + 11)
#define BOOKOO_ERROR_BLE_ADVSTOP_FAIL               (BOOKOO_ERROR_SYS_MODULE_BASE_NUM + 12)
#define BOOKOO_ERROR_BLE_DFUDISCONN_FAIL			(BOOKOO_ERROR_SYS_MODULE_BASE_NUM + 13)
#define BOOKOO_ERROR_CHARGING_INVAILD               (BOOKOO_ERROR_SYS_MODULE_BASE_NUM + 14)
#define BOOKOO_ERROR_MASS_LOWPOWER_PROBE_FAIL       (BOOKOO_ERROR_SYS_MODULE_BASE_NUM + 15)

#define BOOKOO_ERROR_HFCLK_FAIL                     (BOOKOO_ERROR_SYS_PERIPHERAL_BASE_NUM + 1)
#define BOOKOO_ERROR_WDTINIT_FAIL                   (BOOKOO_ERROR_SYS_PERIPHERAL_BASE_NUM + 2)
#define BOOKOO_ERROR_SFUD_INIT_FAIL                 (BOOKOO_ERROR_SYS_PERIPHERAL_BASE_NUM + 0x0110)
#define BOOKOO_ERROR_SFUD_READ_FAIL                 (BOOKOO_ERROR_SYS_PERIPHERAL_BASE_NUM + 0x0120)
#define BOOKOO_ERROR_SFUD_WRITE_FAIL                (BOOKOO_ERROR_SYS_PERIPHERAL_BASE_NUM + 0x0130)
#define BOOKOO_ERROR_SFUD_ERASE_FAIL                (BOOKOO_ERROR_SYS_PERIPHERAL_BASE_NUM + 0x0140)
#define BOOKOO_ERROR_SFUD_ERASEWRITE_FAIL			(BOOKOO_ERROR_SYS_PERIPHERAL_BASE_NUM + 0x0150)
#define BOOKOO_ERROR_SFUD_WAKEUP_FAIL               (BOOKOO_ERROR_SYS_PERIPHERAL_BASE_NUM + 0x0160)
#define BOOKOO_ERROR_SFUD_VERIFY_FAIL               (BOOKOO_ERROR_SYS_PERIPHERAL_BASE_NUM + 0x0170)

/** @defgroup Warning Codes Base number definitions
 * @{ */
#define BOOKOO_WARNING_SYS_RESOURCE_BASE_NUM  	    (0x5100)    ///< System resource level warning base
#define BOOKOO_WARNING_SYS_MODULE_BASE_NUM  		(0x5200)    ///< System module level warning base
#define BOOKOO_WARNING_SYS_PERIPHERAL_BASE_NUM 	    (0x5300)    ///< System peripheral warning base

#define BOOKOO_WARNING_RTOS_QUEUE_FULL              (BOOKOO_WARNING_SYS_RESOURCE_BASE_NUM + 1)
#define BOOKOO_WARNING_APP_STARTUP                  (BOOKOO_WARNING_SYS_RESOURCE_BASE_NUM + 2)

#define BOOKOO_WARNING_BLE_CONN_FAIL                (BOOKOO_WARNING_SYS_MODULE_BASE_NUM + 1)
#define BOOKOO_WARNING_BLE_SEND_WITHOUT_NOTIFY	    (BOOKOO_WARNING_SYS_MODULE_BASE_NUM + 2)
#define BOOKOO_WARNING_BLE_SEND_UNKOWN_CLIENT		(BOOKOO_WARNING_SYS_MODULE_BASE_NUM + 3)
#define BOOKOO_WARNING_BLE_SEND_FIFO_FULL           (BOOKOO_WARNING_SYS_MODULE_BASE_NUM + 4)
#define BOOKOO_WARNING_BLE_ADV_CLOSE_FAIL           (BOOKOO_WARNING_SYS_MODULE_BASE_NUM + 5)
#define BOOKOO_WARNING_BLE_DISCONN_CALI             (BOOKOO_WARNING_SYS_MODULE_BASE_NUM + 6)
#define BOOKOO_WARNING_BLE_UNPACK_FAIL              (BOOKOO_WARNING_SYS_MODULE_BASE_NUM + 7)
//#define BOOKOO_WARNING_CHARGING_INVAILD					(BOOKOO_WARNING_SYS_MODULE_BASE_NUM + 8)
#define BOOKOO_WARNING_SD_LOWPWRENABLE_FAIL			(BOOKOO_WARNING_SYS_MODULE_BASE_NUM + 9)
#define BOOKOO_WARNING_SD_DCDCENABLE_FAIL           (BOOKOO_WARNING_SYS_MODULE_BASE_NUM + 10)

#define BOOKOO_WARNING_USERCFG_VERIFY_FAIL			(BOOKOO_WARNING_SYS_PERIPHERAL_BASE_NUM + 1)
#define BOOKOO_WARNING_BAT_SAMPLE_BUSY              (BOOKOO_WARNING_SYS_PERIPHERAL_BASE_NUM + 2)
#define BOOKOO_WARNING_VER_UNKNOW                   (BOOKOO_WARNING_SYS_PERIPHERAL_BASE_NUM + 3)
#define BOOKOO_WARNING_SFUD_INIT_FAIL               (BOOKOO_WARNING_SYS_PERIPHERAL_BASE_NUM + 4)

#define APP_WARNING_HANDLER(WARNING_CODE)		\
	app_warning_handler_bare(WARNING_CODE);

/** @} */
#ifdef __cplusplus
}
#endif
#endif // NRF_ERROR_H__

/**
  @}
*/
